<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Balance: {0, number, currency}' => 'Баланс: {0, number, currency}',
    'Balance: {0}' => 'Баланс: {0}',
    'Categories' => 'Категории',
    'Hello, {username}!' => 'Привет, {username}!',
    'Home' => 'На главную',
    'News' => 'Новости',
    'Online news' => 'Новости онлайн',
    'Start the journey' => 'начать путешествие',
    'Subscribe to get the latest news' => 'Подпишитесь, чтобы получать последние обновления',
    'Tags' => 'Теги',
    'You are on Category/Index page' => 'Вы на странице категорий',
    'You are on News/Index page' => 'Вы на странице новостей',
    'You are on Tag/Index page' => 'Вы на странице тегов',
    'You {n,plural,
    offset:1
    =0{did not like this}
    =1{liked this}
    one{and one other person liked this}
    other{and # others liked this}
}' => 'Вы {n,plural,
    offset:1
    =0{еще не поставили лайк}
    =1{поставили лайк}
    one{и еще один поставили лайк}
    other{и # других поставили лайк}
}',
    '{n,number} is spelled as {n,spellout}' => 'Число {n,number} прописью: {n, spellout}',
    'Category name: "{name}"' => 'Имя категории: "{name}"',
    'Default value for source language is English' => 'Английский это значение для исходного языка по умолчанию',
    'Go back' => 'Назад',
    'List of news:' => 'Список новостей:',
    'Tag name: "{name}"' => 'Имя тега: "{name}"',
];
